### ISSUE TITLE
Can't autostart

### ISSUE THREAD

**Issue by Budman1758** [arek125/remote-GPIO-control-server#1]
Program works fine from command line via ssh session.  Cannot get it to autostart via rc.local though.  Attached is a copy of my file.  Any ideas?

The pikeyd program in the line above your programs funs fine. 
 
[rc.local.txt](https://github.com/arek125/remote-GPIO-control-server/files/698190/rc.local.txt)

I know this has to be pretty simple.  Thanks for any help.  Great program.

**Comment by mdi-9** [comment]
First call python command and after that point path to server file. Try like this:
`python /home/pi/remote-GPIO-control-server/rgc-server1_1.py`

**Comment by Budman1758** [comment]
That seems to have done the trick!  Thanks!  

(facepalm)  Now than I think about it that should have been pretty obvious.....
