### ISSUE TITLE
<server> not responding

### ISSUE THREAD

**Issue by pcbjonnes** [arek125/remote-GPIO-control-server#2]
My raspberry pi is on a remote network, behind a firewall and on a local ip address. I use ngrok to set up a tunnel to connect to the server. In the client (android) i specify the host name and the external port that is mapped to the local ip and port 8888. When I try to access the server the app reports "xxx not responding. However, if I select "Restart server app" I get respons from the server and it reports that the server has been restarted. I'm connected to the server, but why do I get "xxx not responding" ? Thank you.

**Comment by mdi-9** [comment]
This looks like server can't send response over UDP protocol but receiving request. If "Restart server app" option restarts server app and returns status in dialog, it means that TCP connection is working fine in both ways.
I'm not sure if ngrok tunnel is supporting both TCP and UDP over the same port.

**Comment by pcbjonnes** [comment]
Hi and thanks for your reply. As far as I can see, ngrok UDP does not support it at all, so that's the reason.

**Comment by mdi-9** [comment]
There are better ways to access local ip from internet like:
1. Ask your ISP provider for possibility to open and redirect port from outside.
2. Use VPN server with public ip, create tunnel to local network and redirect port

**Comment by pcbjonnes** [comment]
Thank you. The problem with it is that I am using a 4G router. My telecom operator only shares private IP addresses (10.x.x.x) that I can not access from the internet.

**Comment by mdi-9** [comment]
I will think about adding options 'TCP Only' in next version, it will be slower but will work in case of situactions like that.
There will be also web client available over http. But i'm far from release.

**Comment by pcbjonnes** [comment]
Wow - sounds very nice! Again, thank you!
