### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by pcbjonnes** [arek125/remote-GPIO-control-server#5]
Hi,
Thank you for your work on this application.
I have tried to update from ver 2 to 3, but now I can not connect via web or android app.
I have been following the readme-instructions.

I think it's running...

pi@MyPi:~/rgc $ sudo systemctl status rgc.service
● rgc.service - Remote GPIO Control Server
   Loaded: loaded (/lib/systemd/system/rgc.service; enabled; vendor preset: enab
   Active: active (running) since Sat 2019-09-21 04:11:15 CEST; 4h 4min ago
 Main PID: 873 (python)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/rgc.service
           └─873 /usr/bin/python rgc-server.py

sep. 21 04:11:15 MyPi systemd[1]: Started Remote GPIO Control Server.
sep. 21 04:11:16 MyPi rgc-server.py[873]: Server time: 2019-09-21 04:11:16.2
sep. 21 04:11:16 MyPi rgc-server.py[873]: OUTPUT: GPIO=5 STATE=1
sep. 21 04:11:16 MyPi rgc-server.py[873]: OUTPUT: GPIO=2 STATE=0
sep. 21 04:11:16 MyPi rgc-server.py[873]: OUTPUT: GPIO=4 STATE=0
sep. 21 04:11:16 MyPi rgc-server.py[873]: OUTPUT: GPIO=6 STATE=1

**Comment by mdi-9** [comment]
Hi, what error you have when you trying to connect ? If its about incopatible version then you still running old version of app. Check if in file (/lib/systemd/system/rgc.service) working directory pointing to new version of folder app.

**Comment by pcbjonnes** [comment]
Sorry for bothering you. The error was that I downloaded the new installation file without deleting the old one. The new one was then automatically renamed, which resulted in me installing the old one. Now it works. Thank you for developing this application. Have a nice day.
