### ISSUE TITLE
not working - due to password?

### ISSUE THREAD

**Issue by mountainbiker77** [arek125/remote-GPIO-control-server#6]
Hi,
thanks for this great work!

unfortunately I did not manage to get it working. Installation seemed ok, but server seems to reject password:
ini file is standard, user: pi

what have I done wrong?
Thanks for any help, 
BR, H

pi@raspberrypi:~ $ sudo systemctl start rgc.service
pi@raspberrypi:~ $ sudo systemctl status rgc.service
● rgc.service - Remote GPIO Control Server
   Loaded: loaded (/lib/systemd/system/rgc.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2020-04-29 20:00:25 CEST; 1s ago
  Process: 3208 ExecStart=/usr/bin/python rgc-server.py (code=exited, status=1/FAILURE)
 Main PID: 3208 (code=exited, status=1/FAILURE)
pi@raspberrypi:~ $ journalctl -u rgc.service
-- Logs begin at Thu 2019-02-14 11:11:59 CET, end at Wed 2020-04-29 20:00:40 CEST. --
Apr 29 19:41:08 raspberrypi systemd[1]: Started Remote GPIO Control Server.
Apr 29 19:41:17 raspberrypi python[579]: Server is starting...
Apr 29 19:41:17 raspberrypi python[579]: Please press Ctrl+C to end the program...
Apr 29 19:41:17 raspberrypi python[579]: Traceback (most recent call last):
Apr 29 19:41:17 raspberrypi python[579]:   File "rgc-server.py", line 1326, in <module>
Apr 29 19:41:17 raspberrypi python[579]:     conn, conndb = newDBConnP()
Apr 29 19:41:17 raspberrypi python[579]:   File "rgc-server.py", line 495, in newDBConnP
Apr 29 19:41:17 raspberrypi python[579]:     conn = psycopg2.connect(connectionString)
Apr 29 19:41:17 raspberrypi python[579]:   File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 126, in co
Apr 29 19:41:17 raspberrypi python[579]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Apr 29 19:41:17 raspberrypi python[579]: psycopg2.OperationalError: FATAL:  Passwort-Authentifizierung für Benutzer »pi« fehlg
Apr 29 19:41:17 raspberrypi python[579]: FATAL:  Passwort-Authentifizierung für Benutzer »pi« fehlgeschlagen
Apr 29 19:41:17 raspberrypi systemd[1]: rgc.service: Main process exited, code=exited, status=1/FAILURE
Apr 29 19:41:17 raspberrypi systemd[1]: rgc.service: Failed with result 'exit-code'.
Apr 29 19:41:20 raspberrypi systemd[1]: rgc.service: Service RestartSec=3s expired, scheduling restart.
Apr 29 19:41:20 raspberrypi systemd[1]: rgc.service: Scheduled restart job, restart counter is at 1.
Apr 29 19:41:20 raspberrypi systemd[1]: Stopped Remote GPIO Control Server.
Apr 29 19:41:20 raspberrypi systemd[1]: Started Remote GPIO Control Server.
Apr 29 19:41:21 raspberrypi python[854]: Server is starting...
Apr 29 19:41:21 raspberrypi python[854]: Please press Ctrl+C to end the program...
Apr 29 19:41:21 raspberrypi python[854]: Traceback (most recent call last):
Apr 29 19:41:21 raspberrypi python[854]:   File "rgc-server.py", line 1326, in <module>

pi@raspberrypi:~ $

**Comment by mdi-9** [comment]
Hi, There is problem with postgresql authentication, set proper user and password in ini config file.

**Comment by mountainbiker77** [comment]
HI, thanks for the quick reply!
now I understand!
pi@raspberrypi:~ $ sudo systemctl status rgc.service
● rgc.service - Remote GPIO Control Server
   Loaded: loaded (/lib/systemd/system/rgc.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-04-29 21:30:45 CEST; 391ms ago

however when I repeat this command it says in50% cases  (code=exited, status=1/FAILURE)

and, I dont manage to open it in webbrowser or Android app 
I use Ip from:  hostname -I    and port 80 (like in ini file)
any hints what might wrong are helpful

BR 
H

**Comment by mdi-9** [comment]
Maybe it's restarting, show me: sudo journalctl -u rgc.service -r

**Comment by mountainbiker77** [comment]
Hi, even when status = active (running):

pi@raspberrypi:~ $ sudo systemctl status rgc.service
● rgc.service - Remote GPIO Control Server
   Loaded: loaded (/lib/systemd/system/rgc.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-04-29 22:33:28 CEST; 390ms ago
 Main PID: 8930 (python)
    Tasks: 1 (limit: 2200)
   Memory: 5.8M
   CGroup: /system.slice/rgc.service
           └─8930 /usr/bin/python rgc-server.py

Apr 29 22:33:28 raspberrypi systemd[1]: Started Remote GPIO Control Server.

pi@raspberrypi:~ $ sudo journalctl -u rgc.service -r
-- Logs begin at Thu 2019-02-14 11:11:59 CET, end at Wed 2020-04-29 22:33:33 CEST. --
Apr 29 22:33:33 raspberrypi systemd[1]: rgc.service: Failed with result 'exit-code'.
Apr 29 22:33:33 raspberrypi systemd[1]: rgc.service: Main process exited, code=exited, status=1/FAILURE
Apr 29 22:33:33 raspberrypi python[8946]: FATAL:  Passwort-Authentifizierung für Benutzer »pi« fehlgeschlagen
Apr 29 22:33:33 raspberrypi python[8946]: psycopg2.OperationalError: FATAL:  Passwort-Authentifizierung für Benutzer »pi« fehlgeschlagen
Apr 29 22:33:33 raspberrypi python[8946]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Apr 29 22:33:33 raspberrypi python[8946]:   File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 126, in connect
Apr 29 22:33:33 raspberrypi python[8946]:     conn = psycopg2.connect(connectionString)
Apr 29 22:33:33 raspberrypi python[8946]:   File "rgc-server.py", line 495, in newDBConnP
Apr 29 22:33:33 raspberrypi python[8946]:     conn, conndb = newDBConnP()
Apr 29 22:33:33 raspberrypi python[8946]:   File "rgc-server.py", line 1326, in <module>
Apr 29 22:33:33 raspberrypi python[8946]: Traceback (most recent call last):
Apr 29 22:33:33 raspberrypi python[8946]: Please press Ctrl+C to end the program...
Apr 29 22:33:33 raspberrypi python[8946]: Server is starting...
Apr 29 22:33:32 raspberrypi systemd[1]: Started Remote GPIO Control Server.
Apr 29 22:33:32 raspberrypi systemd[1]: Stopped Remote GPIO Control Server.
Apr 29 22:33:32 raspberrypi systemd[1]: rgc.service: Scheduled restart job, restart counter is at 1077.
Apr 29 22:33:32 raspberrypi systemd[1]: rgc.service: Service RestartSec=3s expired, scheduling restart.
Apr 29 22:33:29 raspberrypi systemd[1]: rgc.service: Failed with result 'exit-code'.
Apr 29 22:33:29 raspberrypi systemd[1]: rgc.service: Main process exited, code=exited, status=1/FAILURE
Apr 29 22:33:29 raspberrypi python[8930]: FATAL:  Passwort-Authentifizierung für Benutzer »pi« fehlgeschlagen
Apr 29 22:33:29 raspberrypi python[8930]: psycopg2.OperationalError: FATAL:  Passwort-Authentifizierung für Benutzer »pi« fehlgeschlagen
Apr 29 22:33:29 raspberrypi python[8930]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
lines 1-23

**Comment by mdi-9** [comment]
Its active only for couple seconds end restarts.
Problem is still the same, make sure if your postgresql user and data base is properly created and inserted into config, or repeat this steps of installation and create root user with privileges of super user.

**Comment by mountainbiker77** [comment]
Hi, 
this was it !
proper linux user password specified in ini file (stupid thing, my mistake)

many thanks, now everything is working, also android app. (except automation tab in android app does not activate...)
This is really nicely programmend!! It offers so many control possibilites, highly complex automation etc. Congratulation for this masterpiece work!
Now I just need to find out the best way to control it from the outside world of the router. 
VPN or port forwarding ?

many thanks again,
H

**Comment by mdi-9** [comment]
Glad to hear. 
As for remote access thare are many options, best is to have public ip address, if you have it ask your ISP for posibility of open at last one port, and then on your local router forward this port to pi device.
VPN option is more secure but there is much more work to set it up.
