### ISSUE TITLE
Problem with DHT11

### ISSUE THREAD

**Issue by WaaCat** [arek125/remote-GPIO-control-server#8]
Hi. I did all way to use DHT11 sensors on Raspberry Pi 3A+ and Model B. Connection is correct and scripts working good. Unfortunately I have this kind of issue :

![pi1](https://user-images.githubusercontent.com/82840257/115291025-883dac00-a154-11eb-8aae-e6c88e9525f8.JPG)
![pi2](https://user-images.githubusercontent.com/82840257/115291037-8a076f80-a154-11eb-939a-691182bf45da.JPG)

I checked my way at two models Raspberry and I have this same kind of problem. I'm looking for solution but maybe you know what can be a problem?

**Comment by mdi-9** [comment]
Hi, I face similar problem with DHT Adafruit library but on Pi 4B, there was a problem with hardware detection. 

I created fork of that lib with fix for Pi 4B (https://github.com/arek125/Adafruit_Python_DHT), 

Not sure if its gona work with Pi 3 but You can try it.

**Comment by WaaCat** [comment]
OK, I found solution to my problem. Finally i used other sensor DHT11 (module type without LED). Type with LED isn't working and GPIO communication failed. 
Second step was modification in file : https://github.com/adafruit/Adafruit_Python_DHT/issues/61 .
Now all working good.
